name: "KM Syncer action"
description: "Action to run KM Syncer App"

runs:
  using: docker
  image: "Dockerfile"
  args:
    - ${{ inputs.app_id }}
    - ${{ inputs.app_private_key }}
    - ${{ inputs.lib_repo_name }}
    - ${{ inputs.jira_host }}
inputs:
  app_id:
    description: "App id of the KM Syncer app."
    required: true
  app_private_key:
    description: "Private key generated for the installed KM Syncer App."
    required: true
  lib_repo_name:
    description: "Name of the repository with common-lib."
    required: true
    default: "be-keto-mojo-common-lib"
  jira_host:
    description: "Base url to JIRA board."
    required: false
    default: "https://keto-mojo.atlassian.net/"
