name: "Hello world!"
description: "Simple acton."

runs:
  using: docker
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
outputs:
  time:
    description: "The time you invoked the action"
  pr_number:
    description: "The number of PR, eg. [BACK-42]"
